/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewersRouteImport } from './routes/reviewers'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionIdRouteImport } from './routes/session.$id'
import { Route as ReviewerAcceptRouteImport } from './routes/reviewer/accept'
import { Route as CoursesIdRouteImport } from './routes/courses.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewersRoute = ReviewersRouteImport.update({
  id: '/reviewers',
  path: '/reviewers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewerAcceptRoute = ReviewerAcceptRouteImport.update({
  id: '/reviewer/accept',
  path: '/reviewer/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CoursesRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/calendar': typeof CalendarRoute
  '/courses': typeof CoursesRouteWithChildren
  '/device': typeof DeviceRoute
  '/exports': typeof ExportsRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/insights': typeof InsightsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/reviewers': typeof ReviewersRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$id': typeof CoursesIdRoute
  '/reviewer/accept': typeof ReviewerAcceptRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/calendar': typeof CalendarRoute
  '/courses': typeof CoursesRouteWithChildren
  '/device': typeof DeviceRoute
  '/exports': typeof ExportsRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/insights': typeof InsightsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/reviewers': typeof ReviewersRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$id': typeof CoursesIdRoute
  '/reviewer/accept': typeof ReviewerAcceptRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/calendar': typeof CalendarRoute
  '/courses': typeof CoursesRouteWithChildren
  '/device': typeof DeviceRoute
  '/exports': typeof ExportsRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/insights': typeof InsightsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/reviewers': typeof ReviewersRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$id': typeof CoursesIdRoute
  '/reviewer/accept': typeof ReviewerAcceptRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/calendar'
    | '/courses'
    | '/device'
    | '/exports'
    | '/friends'
    | '/history'
    | '/insights'
    | '/leaderboard'
    | '/login'
    | '/progress'
    | '/reviewers'
    | '/settings'
    | '/simulator'
    | '/auth/callback'
    | '/courses/$id'
    | '/reviewer/accept'
    | '/session/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/calendar'
    | '/courses'
    | '/device'
    | '/exports'
    | '/friends'
    | '/history'
    | '/insights'
    | '/leaderboard'
    | '/login'
    | '/progress'
    | '/reviewers'
    | '/settings'
    | '/simulator'
    | '/auth/callback'
    | '/courses/$id'
    | '/reviewer/accept'
    | '/session/$id'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/calendar'
    | '/courses'
    | '/device'
    | '/exports'
    | '/friends'
    | '/history'
    | '/insights'
    | '/leaderboard'
    | '/login'
    | '/progress'
    | '/reviewers'
    | '/settings'
    | '/simulator'
    | '/auth/callback'
    | '/courses/$id'
    | '/reviewer/accept'
    | '/session/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  CalendarRoute: typeof CalendarRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DeviceRoute: typeof DeviceRoute
  ExportsRoute: typeof ExportsRoute
  FriendsRoute: typeof FriendsRoute
  HistoryRoute: typeof HistoryRoute
  InsightsRoute: typeof InsightsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  ProgressRoute: typeof ProgressRoute
  ReviewersRoute: typeof ReviewersRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ReviewerAcceptRoute: typeof ReviewerAcceptRoute
  SessionIdRoute: typeof SessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewers': {
      id: '/reviewers'
      path: '/reviewers'
      fullPath: '/reviewers'
      preLoaderRoute: typeof ReviewersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewer/accept': {
      id: '/reviewer/accept'
      path: '/reviewer/accept'
      fullPath: '/reviewer/accept'
      preLoaderRoute: typeof ReviewerAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoursesRouteChildren {
  CoursesIdRoute: typeof CoursesIdRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesIdRoute: CoursesIdRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  CalendarRoute: CalendarRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DeviceRoute: DeviceRoute,
  ExportsRoute: ExportsRoute,
  FriendsRoute: FriendsRoute,
  HistoryRoute: HistoryRoute,
  InsightsRoute: InsightsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  ProgressRoute: ProgressRoute,
  ReviewersRoute: ReviewersRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ReviewerAcceptRoute: ReviewerAcceptRoute,
  SessionIdRoute: SessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
